# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.cache/wt [current_project]
set_property parent.project_path /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Generic_counter.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/VGA_Driver.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Multiplexer_4way.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Snake_control.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/7Segment_Display_Interface.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/VGA_Interface.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Target_Generator.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Navigation_State_Machine.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Master_State_Machine.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Score_Counter.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/sources_1/new/Master_Game.v
}
read_xdc /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/constrs_1/new/Snake_Constr.xdc
set_property used_in_implementation false [get_files /afs/inf.ed.ac.uk/user/s14/s1443062/iron-man/snake_game.srcs/constrs_1/new/Snake_Constr.xdc]

synth_design -top Master_Game -part xc7a35tcpg236-1
write_checkpoint -noxdef Master_Game.dcp
catch { report_utilization -file Master_Game_utilization_synth.rpt -pb Master_Game_utilization_synth.pb }
