# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/inf.ed.ac.uk/user/s14/s1443062/snake_game/snake_game.cache/wt [current_project]
set_property parent.project_path /afs/inf.ed.ac.uk/user/s14/s1443062/snake_game/snake_game.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /afs/inf.ed.ac.uk/user/s14/s1443062/snake_game/snake_game.srcs/sources_1/new/Generic_counter.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/snake_game/snake_game.srcs/sources_1/new/VGA_Driver.v
  /afs/inf.ed.ac.uk/user/s14/s1443062/snake_game/snake_game.srcs/sources_1/new/VGA_Interface.v
}
synth_design -top VGA_Interface -part xc7a35tcpg236-1
write_checkpoint -noxdef VGA_Interface.dcp
catch { report_utilization -file VGA_Interface_utilization_synth.rpt -pb VGA_Interface_utilization_synth.pb }
